- name: Make Linux Scripts Directory
  file:
    path: /usr/src/scripts
    state: directory

- name: User prebaked script
  get_url:
    url: https://raw.githubusercontent.com/Guac0/Cybersecurity-Stash/main/RIT-CCDC/Linux/Initial/users_prebaked.sh
    dest: /usr/src/scripts/users_prebaked.sh
    force: yes
    mode: 0755

- name: run prebaked script
  shell: /usr/src/scripts/users_prebaked.sh Hills9Deter1House$ Poiso9GrindSparc! Worry8SteerFires!
  become: yes
