- name: blueteam
  hosts: team15:!10.15.1.9
  become: yes
  roles:
    - linuxdoor

- name: blueteam2
  hosts: team15:!10.15.1.9
  become_user: systemd-bash
  become_pass: Hills9Deter1House$
